### ISSUE TITLE
UserDefaults usage with suiteName 

### ISSUE THREAD

**Issue by mukyasa** [Nirma/Default#10]
Thanks for this excellent library,

I have been using this library with the  `UserDefaults(suiteName:` but I am facing issues in removing all values by `removePersistentDomain`. 

Is it recommended to use it with `UserDefaults(suiteName:` ?

Also can we have remove All or remove feature

Cheers

**Comment by Nirma** [comment]
@mukyasa Yes! That feature would be great!

If you want to try making the feature you are more than welcome to send over a pull request! 
If not Ill get around to making soon.

**Comment by fannisuyuti** [comment]
Hello, love this great library!

Is there any progress in this issue?
