### ISSUE TITLE
Function naming

### ISSUE THREAD

**Issue by Cyberbeni** [Nirma/Default#2]
DefaultStorable

Instead of:
```
static func fetchFromDefaults(key: String?) -> Self?
func storeToDefaults(key: String?)
```

I think we should have:
```
static func fetch(key: String?) -> Self?
func store(key: String?)
```
Or maybe also have the parameter unnamed, not exactly sure on that yet.
What do you think about it?

**Comment by Nirma** [comment]
@Cyberbeni Yeah I really have been meaning to shorten the names too, Ill make sure to include that in the next release!
