### ISSUE TITLE
Clear key

### ISSUE THREAD

**Issue by nitrag** [Nirma/Default#7]
What would the proper method for clearing a stored object?

Would be nice to have:
```swift
var me: User? = nil
me = User(...)
me.write()
....
//logout
me.clear()
print(me) --> nil
me.read() --> nil
```

**Comment by Nirma** [comment]
@nitrag Sorry for the delay, yeah this is a great idea and something I feel bad about leaving out.
Ill roll out a release with this soon, if you feel up to it you are more than welcome to implement the feature!

**Comment by nitrag** [comment]
Currently I'm just using:

```swift
UserDefaults.standard.removeObject(forKey: "current_logged_in_user")
```

So does that mean we just need:

```swift
public func clear(withKey key: String? = nil) {
    let key: String = key ?? Self.defaultIdentifier
    Self.defaults.df.removeObject(forKey: key)
}
```

I feel like it should be more complicated than that.

**Comment by Nirma** [comment]
@nitrag I think thats actually how it would look! 👍 

Looks like you got it, if you want you can send that over and we can think about writing some tests and if it looks fine then kick out a release!

**Comment by Nirma** [comment]
@nitrag Ill take care of the tests so just sending that over is great!
