### ISSUE TITLE
Seemengly crashes when model of class is changed

### ISSUE THREAD

**Issue by jacobokoenig** [Nirma/Default#9]
Hi,

Not sure if this is chance or not, but it happened to me twice that fetch crashed after the model (variables) of my class changed. Since changing the model on upgrades is a fairly common thing, I wonder if this can be somehow avoided/repaired?

**Comment by Nirma** [comment]
@jacobo360  Im sorry for this inconvenience, if you have the details can you tell me a little bit more about the crash and the code surrounding the call site?

Thanks so much for opening the issue!

**Comment by Nirma** [comment]
@jacobo360 Im going to open an issue where everyone can chime in with what they would like added and fixed, would you mind joining?
